import fs from 'node:fs';

const BASE=(process.env.TARGET_URL||'https://tijra-production.up.railway.app').replace(/\/$/,'');
const RUN_ID=new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14);
const PASSWORD=`Qa!${RUN_ID}pass`;
const report={runId:RUN_ID,target:BASE,checks:[],counters:{accounts:0,products:0,orders:0,picks:0,receives:0,sales:0},verdict:'NOT PRODUCTION READY'};
fs.mkdirSync('artifacts',{recursive:true});

class Client{constructor(name){this.name=name;this.cookie='';}async req(path,{method='GET',body}={}){const headers={accept:'application/json'};if(this.cookie)headers.cookie=this.cookie;if(body!==undefined){headers['content-type']='application/json';body=JSON.stringify(body);}let res;try{res=await fetch(BASE+path,{method,headers,body,redirect:'manual',signal:AbortSignal.timeout(20000)});}catch(e){return{status:0,json:null,text:String(e)}}const sc=typeof res.headers.getSetCookie==='function'?res.headers.getSetCookie():[res.headers.get('set-cookie')].filter(Boolean);for(const x of sc){const c=x.split(';')[0];if(c.includes('='))this.cookie=c;}const text=await res.text();let json=null;try{json=text?JSON.parse(text):null}catch{}return{status:res.status,json,text};}}
function check(name,ok,expected,actual,critical=false){report.checks.push({name,status:ok?'PASS':'FAIL',expected,actual,critical});console.log(`${ok?'PASS':'FAIL'} ${name} :: ${actual}`);}
async function register(type,i,activity){const c=new Client(`${type}-${i}`);const email=`qa.${RUN_ID}.${type.toLowerCase()}.${i}@example.test`;const body={name:`QA ${type} ${i}`,email,password:PASSWORD,businessName:`QA ${type} ${RUN_ID} ${i}`,businessType:type,businessActivity:activity,city:'Jeddah'};const r=await c.req('/api/auth/register',{method:'POST',body});check(`register ${type} ${i}`,r.status===201,'201',`${r.status} ${r.json?.error||''}`,true);if(r.status===201)report.counters.accounts++;return{client:c,email,body,business:r.json?.business};}
async function publish(a,i,over={}){const body={name:`QA Product ${RUN_ID} ${a.business.id.slice(-4)} ${i}`,sku:`QA-${RUN_ID}-${a.business.id.slice(-4)}-${i}`,barcode:`629${RUN_ID.slice(-10)}${String(i).padStart(4,'0')}${a.business.id.slice(-2)}`.slice(0,40),category:i%2?'مشروبات':'مواد غذائية',activity:a.business.businessActivity||'OTHER',unit:i%3===0?'piece':i%3===1?'box':'kg',price:10+i,quantity:100,minOrderQty:1,...over};const r=await a.client.req('/api/marketplace/listings',{method:'POST',body});check(`publish ${body.sku}`,r.status===201||r.status===200,'201/200',`${r.status} ${r.json?.error||''}`);if(r.status===201)report.counters.products++;return{owner:a,...body,listing:r.json?.listing};}
async function status(c,id,action){return c.req(`/api/marketplace/orders/${id}/status`,{method:'PATCH',body:{action}})}
async function pick(c,id,barcode){return c.req(`/api/marketplace/orders/${id}/pick`,{method:'POST',body:{barcode}})}
async function products(a){return a.client.req('/api/products')}

const health=await new Client('health').req('/api/health');check('health',health.status===200&&health.json?.ok===true,'200 ok=true',`${health.status} ${JSON.stringify(health.json)}`,true);report.build=health.json?.build||null;if(health.status!==200)throw new Error('health failed');

const suppliers=[];const retailers=[];for(let i=1;i<=3;i++)suppliers.push(await register('SUPPLIER',i,'OTHER'));for(let i=1;i<=3;i++)retailers.push(await register('RETAILER',i,i===1?'GROCERY':i===2?'CAFE':'RESTAURANT'));const both=await register('BOTH',1,'GROCERY');

const a=suppliers[0];const wrong=new Client('wrong');let r=await wrong.req('/api/auth/login',{method:'POST',body:{email:a.email,password:PASSWORD+'x'}});check('wrong password rejected',r.status===401,'401',`${r.status} ${r.json?.error||''}`);const dup=new Client('dup');r=await dup.req('/api/auth/register',{method:'POST',body:a.body});check('duplicate email rejected',r.status===409,'409',`${r.status} ${r.json?.error||''}`);

const listings=[];for(const s of suppliers){for(let i=1;i<=10;i++)listings.push(await publish(s,i));}check('30 products published',report.counters.products>=30,'>=30',String(report.counters.products),true);
for(const x of listings.filter(x=>x.listing)){for(const [k,v] of [['sku',x.sku],['barcode',x.barcode]]){const q=await x.owner.client.req(`/api/marketplace/listings?${k}=${encodeURIComponent(v)}`);check(`persist ${k} ${x.sku}`,q.status===200&&q.json?.exists===true,'exists=true',`${q.status} ${q.json?.exists}`);}}

const sellerByBusiness=new Map(suppliers.map(s=>[s.business.id,s]));const listingById=new Map(listings.filter(x=>x.listing).map(x=>[x.listing.id,x]));const lifecycle=[];
for(let i=0;i<10;i++){const s=suppliers[i%3];const mine=listings.filter(x=>x.owner.business.id===s.business.id&&x.listing);const l1=mine[(i*2)%mine.length],l2=mine[(i*2+1)%mine.length];const buyer=retailers[i%3];const or=await buyer.client.req('/api/marketplace/orders',{method:'POST',body:{items:[{listingId:l1.listing.id,quantity:5},{listingId:l2.listing.id,quantity:5}]}});check(`order ${i+1}`,or.status===201,'201',`${or.status} ${or.json?.error||''}`,true);if(or.status===201){report.counters.orders+=(or.json?.orders||[]).length||1;lifecycle.push({buyer,seller:sellerByBusiness.get(or.json.order.sellerBusinessId),order:or.json.order});}}

for(const row of lifecycle){const {buyer,seller,order}=row;let x=await status(seller.client,order.id,'ACCEPT');check(`accept ${order.id.slice(-8)}`,x.status===200,'200',`${x.status} ${x.json?.error||''}`);x=await status(buyer.client,order.id,'RECEIVE');check(`receive blocked before pick ${order.id.slice(-8)}`,x.status===409&&x.json?.error==='PICK_NOT_COMPLETE','409 PICK_NOT_COMPLETE',`${x.status} ${x.json?.error||''}`,true);const first=order.items[0],fl=listingById.get(first.listingId);x=await pick(seller.client,order.id,'WRONG-BARCODE');check(`wrong barcode ${order.id.slice(-8)}`,x.status===409,'409',`${x.status} ${x.json?.error||''}`);x=await pick(seller.client,order.id,fl.barcode);if(x.status===200)report.counters.picks++;check(`partial pick ${order.id.slice(-8)}`,x.status===200,'200',`${x.status} ${x.json?.item?.scanned||''}`);x=await status(buyer.client,order.id,'RECEIVE');check(`receive blocked partial ${order.id.slice(-8)}`,x.status===409&&x.json?.error==='PICK_NOT_COMPLETE','409 PICK_NOT_COMPLETE',`${x.status} ${x.json?.error||''}`,true);for(const item of order.items){const l=listingById.get(item.listingId);const already=item.id===first.id?1:0;for(let n=already;n<Number(item.quantity);n++){const p=await pick(seller.client,order.id,l.barcode);if(p.status===200)report.counters.picks++;check(`pick ${order.id.slice(-8)} ${l.sku} ${n+1}/${item.quantity}`,p.status===200,'200',`${p.status} ${p.json?.error||p.json?.item?.scanned||''}`);}}x=await pick(seller.client,order.id,fl.barcode);check(`extra pick rejected ${order.id.slice(-8)}`,x.status===409&&x.json?.error==='ITEM_ALREADY_COMPLETE','409 ITEM_ALREADY_COMPLETE',`${x.status} ${x.json?.error||''}`);x=await status(buyer.client,order.id,'RECEIVE');if(x.status===200)report.counters.receives++;check(`receive complete ${order.id.slice(-8)}`,x.status===200,'200',`${x.status} ${x.json?.error||''}`,true);x=await status(buyer.client,order.id,'RECEIVE');check(`double receive rejected ${order.id.slice(-8)}`,x.status===409,'409',`${x.status} ${x.json?.error||''}`,true);}

const low=await publish(suppliers[0],8001,{name:`QA Low ${RUN_ID}`,sku:`QA-${RUN_ID}-LOW`,barcode:`629${RUN_ID.slice(-10)}8001`,quantity:1,minOrderQty:1});if(low.listing){r=await retailers[0].client.req('/api/marketplace/orders',{method:'POST',body:{listingId:low.listing.id,quantity:2}});check('overstock rejected',r.status===409&&r.json?.error==='INSUFFICIENT_STOCK','409 INSUFFICIENT_STOCK',`${r.status} ${r.json?.error||''}`);}
const min=await publish(suppliers[0],8002,{name:`QA Min ${RUN_ID}`,sku:`QA-${RUN_ID}-MIN`,barcode:`629${RUN_ID.slice(-10)}8002`,quantity:10,minOrderQty:3});if(min.listing){r=await retailers[0].client.req('/api/marketplace/orders',{method:'POST',body:{listingId:min.listing.id,quantity:1}});check('below minimum rejected',r.status===409&&r.json?.error==='BELOW_MINIMUM','409 BELOW_MINIMUM',`${r.status} ${r.json?.error||''}`);}
const self=await publish(both,8003,{name:`QA Self ${RUN_ID}`,sku:`QA-${RUN_ID}-SELF`,barcode:`629${RUN_ID.slice(-10)}8003`,quantity:10,minOrderQty:1});if(self.listing){r=await both.client.req('/api/marketplace/orders',{method:'POST',body:{listingId:self.listing.id,quantity:1}});check('self order rejected',r.status===409&&r.json?.error==='SELF_ORDER_NOT_ALLOWED','409 SELF_ORDER_NOT_ALLOWED',`${r.status} ${r.json?.error||''}`);}

for(const retailer of retailers){const pr=await products(retailer);const ours=(pr.json?.products||[]).filter(p=>String(p.name||'').includes('QA Product')&&Number(p.quantity)>0);let n=0;while(n<18&&report.counters.sales<50&&ours.length){const p=ours[n%ours.length];const latest=await products(retailer);const lp=(latest.json?.products||[]).find(z=>z.id===p.id);if(!lp||Number(lp.quantity)<1){n++;continue;}const body={invoiceNumber:`QA-${RUN_ID}-POS-${retailer.business.id.slice(-4)}-${n}`,paymentMethod:n%2?'CARD':'CASH',items:[{productId:lp.id,quantity:1,unitPrice:Number(lp.salePrice)}]};const sr=await retailer.client.req('/api/sales',{method:'POST',body});check(`POS ${retailer.business.id.slice(-4)} ${n}`,sr.status===201,'201',`${sr.status} ${sr.json?.error||''}`);if(sr.status===201)report.counters.sales++;n++;}}
check('50 POS sales',report.counters.sales>=50,'>=50',String(report.counters.sales),true);

for(const retailer of retailers){const pr=await products(retailer);const neg=(pr.json?.products||[]).filter(p=>Number(p.quantity)<0);check(`no negative stock ${retailer.business.id.slice(-5)}`,neg.length===0,'0',String(neg.length),true);}

const fails=report.checks.filter(x=>x.status==='FAIL');report.verdict=fails.length?'NOT PRODUCTION READY':'PRODUCTION READY';report.finishedAt=new Date().toISOString();report.summary={pass:report.checks.filter(x=>x.status==='PASS').length,fail:fails.length,criticalFails:fails.filter(x=>x.critical).map(x=>x.name)};fs.writeFileSync('artifacts/tijra-e2e-report.json',JSON.stringify(report,null,2));fs.writeFileSync('artifacts/tijra-e2e-report.md',[`# Tijra E2E ${RUN_ID}`,`Build: ${report.build}`,`Verdict: ${report.verdict}`,`Counters: ${JSON.stringify(report.counters)}`,...report.checks.map(x=>`${x.status} | ${x.name} | ${x.actual}`)].join('\n'));console.log('FINAL',report.verdict,report.counters);if(fails.length)process.exitCode=1;
