import fs from 'node:fs';
import { chromium, firefox, webkit, devices } from 'playwright';

const BASE=(process.env.TARGET_URL||'https://tijra-production.up.railway.app').replace(/\/$/,'');
const RUN=Date.now().toString(36);const PW=`Qa!${RUN}pass`;fs.mkdirSync('artifacts/browser',{recursive:true});
const out={run:RUN,target:BASE,build:null,profiles:[],checks:[],blocked:[],verdict:'NOT PRODUCTION READY'};
function ck(profile,name,ok,actual,expected='PASS'){out.checks.push({profile,name,status:ok?'PASS':'FAIL',expected,actual});console.log(`${ok?'PASS':'FAIL'} | ${profile} | ${name} | ${actual}`)}
function blocked(profile,name,reason){out.blocked.push({profile,name,status:'BLOCKED',reason});console.log(`BLOCKED | ${profile} | ${name} | ${reason}`)}
async function noOverflow(page,profile,label){const x=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));ck(profile,`${label} no document horizontal overflow`,x.sw<=x.cw+3,`scrollWidth=${x.sw} clientWidth=${x.cw}`)}
async function noAppError(page,profile,label){const body=(await page.locator('body').innerText()).slice(0,20000);ck(profile,`${label} renders without fatal UI error`,!/(Application error|Internal Server Error|This page could not be found|500 Internal)/i.test(body),body.match(/Application error|Internal Server Error|500 Internal/i)?.[0]||'no fatal marker')}
async function registerUI(page,profile,type,index){await page.goto(`${BASE}/login?mode=register`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForSelector('#email');if(type==='SUPPLIER')await page.getByRole('button',{name:/مورد/}).click();if(type==='BOTH')await page.getByRole('button',{name:/الاثنان/}).click();const email=`qa.${RUN}.${profile.replace(/[^a-z0-9]/gi,'').toLowerCase()}.${type.toLowerCase()}.${index}@example.test`;await page.locator('#name').fill(`QA ${profile} ${type}`);await page.locator('#phone').fill('0500000000');await page.locator('#businessName').fill(`QA ${profile} ${type} ${RUN}`);await page.locator('#city').fill('جدة');await page.locator('#email').fill(email);await page.locator('#password').fill(PW);await page.getByRole('button',{name:'إنشاء الحساب والمتابعة'}).click();await page.waitForURL(type==='SUPPLIER'?/\/marketplace\/seller/:/\/marketplace(?:\?|$)/,{timeout:30000});ck(profile,`UI register ${type}`,true,page.url());return{email,password:PW}}
async function loginUI(page,profile,acct){await page.context().clearCookies();await page.goto(`${BASE}/login`,{waitUntil:'domcontentloaded',timeout:30000});await page.locator('#email').fill(acct.email);await page.locator('#password').fill(acct.password);await page.getByRole('button',{name:'تسجيل الدخول'}).click();await page.waitForURL(u=>new URL(u).pathname!='/login',{timeout:30000});ck(profile,'UI login after fresh session',true,page.url())}
async function supplierFlow(page,profile){const acct=await registerUI(page,profile,'SUPPLIER',1);await page.getByRole('heading',{name:'متجرك في تِجرا'}).waitFor({timeout:20000});await noOverflow(page,profile,'supplier dashboard');await noAppError(page,profile,'supplier dashboard');
 const name=`QA Browser Product ${RUN} ${profile}`;const sku=`QA-${RUN}-${profile.replace(/[^A-Z0-9]/gi,'').toUpperCase()}-UI`;const barcode=`629${Date.now()}${Math.floor(Math.random()*1000)}`;
 const submit=page.getByRole('button',{name:'نشر المنتج في السوق'});const form=submit.locator('xpath=ancestor::form');await form.locator('input[name=name]').fill(name);await form.locator('input[name=category]').fill('اختبار متصفح');await form.locator('input[name=barcode]').fill(barcode);await form.locator('input[name=sku]').fill(sku);await form.locator('input[name=price]').fill('25.5');await form.locator('input[name=quantity]').fill('12');await form.locator('input[name=minOrderQty]').fill('2');await form.locator('select[name=unit]').selectOption('piece');await submit.click();await page.getByRole('status').filter({hasText:/تم نشر المنتج|منشور بالفعل/}).waitFor({timeout:30000});ck(profile,'publish product through UI',true,`${sku} ${barcode}`);await page.reload({waitUntil:'domcontentloaded'});await page.getByText(sku,{exact:false}).first().waitFor({timeout:20000});ck(profile,'published product persists after refresh',true,sku);
 // Scanner dialog and camera initialization. Chromium gets a fake media device in launch args.
 const scan=page.getByRole('button',{name:'مسح الباركود بالكاميرا'}).first();if(await scan.count()){await scan.click();const dlg=page.getByRole('dialog',{name:'ماسح الباركود'});await dlg.waitFor({timeout:10000});ck(profile,'barcode scanner dialog opens',true,'dialog visible');await page.waitForTimeout(1200);const err=await dlg.locator('.barcodeScannerError').textContent().catch(()=>null);if(err)blocked(profile,'camera media stream',err.trim());else ck(profile,'camera media stream initializes',true,'no scanner initialization error');await dlg.getByRole('button',{name:'إغلاق الماسح'}).click();}
 await loginUI(page,profile,acct);await page.goto(`${BASE}/marketplace/seller`,{waitUntil:'domcontentloaded'});await page.getByText(sku,{exact:false}).first().waitFor({timeout:20000});ck(profile,'published product persists after logout/login',true,sku);
 for(const path of ['/supplier/picking','/supplier/alerts','/supplier/forecast','/supplier/stock-count','/supplier/pricing']){await page.goto(BASE+path,{waitUntil:'domcontentloaded',timeout:30000});await noAppError(page,profile,path);await noOverflow(page,profile,path)}
 return{acct,sku};}
async function csvImport(page,profile){await page.goto(`${BASE}/supplier/import`,{waitUntil:'domcontentloaded',timeout:30000});const csv=['name,sku,barcode,category,unit,price,quantity,minOrderQty',`QA CSV One ${RUN},QA-${RUN}-CSV1,629${Date.now()}11,QA,piece,12,9,1`,`QA CSV Two ${RUN},QA-${RUN}-CSV2,629${Date.now()}22,QA,box,22,8,2`].join('\n');const input=page.locator('input[type=file][accept*="csv"]');await input.setInputFiles({name:`qa-${RUN}.csv`,mimeType:'text/csv',buffer:Buffer.from(csv)});await page.getByText('صف صالح للاستيراد',{exact:false}).waitFor({timeout:10000});const button=page.getByRole('button',{name:/استيراد/});await button.click();await page.getByText(/اكتمل الاستيراد/).waitFor({timeout:30000});const msg=await page.getByText(/اكتمل الاستيراد/).innerText();ck(profile,'CSV file upload and import',/ناجح/.test(msg)&&!/تعذر/.test(msg),msg,'all rows successful');await noOverflow(page,profile,'supplier import')}
async function retailerFlow(page,profile){await page.context().clearCookies();await registerUI(page,profile,'RETAILER',2);await noOverflow(page,profile,'retailer marketplace');await noAppError(page,profile,'retailer marketplace');for(const path of ['/marketplace','/inventory','/sales','/smart-buy','/alerts','/employees','/payroll','/accounting','/inventory/waste','/inventory/returns','/inventory/locations']){await page.goto(BASE+path,{waitUntil:'domcontentloaded',timeout:30000});await noAppError(page,profile,path);await noOverflow(page,profile,path)}}
async function runProfile(p){const start=Date.now();let browser;const errors=[];try{browser=await p.engine.launch({headless:true,args:p.fakeCamera?['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']:[]});const context=await browser.newContext(p.contextOptions||{});const page=await context.newPage();page.on('pageerror',e=>errors.push(`pageerror:${e.message}`));page.on('console',m=>{if(m.type()==='error')errors.push(`console:${m.text()}`)});page.on('requestfailed',r=>{if(r.url().startsWith(BASE))errors.push(`requestfailed:${r.url()} ${r.failure()?.errorText}`)});const h=await context.request.get(`${BASE}/api/health`);if(h.ok()){const j=await h.json();out.build=out.build||j.build;ck(p.name,'health in browser context',j.ok===true,`${h.status()} build=${j.build}`)}else ck(p.name,'health in browser context',false,String(h.status()),'200');await supplierFlow(page,p.name);if(p.csv)await csvImport(page,p.name);await retailerFlow(page,p.name);await page.screenshot({path:`artifacts/browser/${p.name}.png`,fullPage:true});const serious=errors.filter(x=>!/favicon|ERR_ABORTED|camera|NotFoundException/i.test(x));ck(p.name,'no unhandled browser/runtime errors',serious.length===0,serious.slice(0,8).join(' | ')||'none');out.profiles.push({name:p.name,status:serious.length?'FAIL':'PASS',durationMs:Date.now()-start,errors:serious});await context.close();}catch(e){out.profiles.push({name:p.name,status:'FAIL',durationMs:Date.now()-start,error:String(e)});ck(p.name,'profile completed',false,String(e));try{if(browser){const ps=browser.contexts?.()||[];for(const c of ps){const pages=c.pages();if(pages[0])await pages[0].screenshot({path:`artifacts/browser/${p.name}-failure.png`,fullPage:true})}}}catch{}}finally{await browser?.close()}}
const profiles=[
 {name:'chromium-desktop',engine:chromium,contextOptions:{viewport:{width:1440,height:900}},fakeCamera:true,csv:true},
 {name:'firefox-desktop',engine:firefox,contextOptions:{viewport:{width:1440,height:900}}},
 {name:'webkit-desktop',engine:webkit,contextOptions:{viewport:{width:1440,height:900}}},
 {name:'iphone-15',engine:webkit,contextOptions:{...devices['iPhone 15']}},
 {name:'pixel-7',engine:chromium,contextOptions:{...devices['Pixel 7']},fakeCamera:true},
];
for(const p of profiles)await runProfile(p);
const fails=out.checks.filter(x=>x.status==='FAIL');out.verdict=fails.length?'NOT PRODUCTION READY':'PRODUCTION READY';out.finishedAt=new Date().toISOString();out.summary={pass:out.checks.filter(x=>x.status==='PASS').length,fail:fails.length,blocked:out.blocked.length,profiles:out.profiles};fs.writeFileSync('artifacts/tijra-browser-report.json',JSON.stringify(out,null,2));fs.writeFileSync('artifacts/tijra-browser-report.md',[`# Tijra Browser QA ${RUN}`,`Build: ${out.build}`,`Verdict: ${out.verdict}`,`Pass: ${out.summary.pass} Fail: ${out.summary.fail} Blocked: ${out.summary.blocked}`,...out.checks.map(x=>`${x.status} | ${x.profile} | ${x.name} | ${x.actual}`),...out.blocked.map(x=>`BLOCKED | ${x.profile} | ${x.name} | ${x.reason}`)].join('\n'));console.log('FINAL',out.verdict,out.summary);if(fails.length)process.exitCode=1;
